frontend/index.html

[FE] 프론트엔드 디렉토리 추가

---

backend/diagram.drawio

기획서를 바탕으로 객체 다이어그램을 그렸습니다.
현재 결과물은 구현 과정에서 수정이 있을 수 있습니다.
- 도메인 객체 다이어그램 그리기

[BE] 도메인 객체 다이어그램 그리기

---

backend/README.md
backend/build.gradle
backend/docker/local-database.yml
backend/src/main/resources/application.properties

도커를 이용해 로컬 환경에서 MySQL 컨테이너를 실행하고,
스프링부트 프로젝트와 데이터베이스를 연결하는 작업을 진행했습니다.
- 도커를 이용한 로컬 데이터베이스 실행을 위해 `docker-compose` 파일 (`.yml`) 추가
- `backend/README.md` 내 로컬 데이터베이스 실행 명령어 추가
- 스프링부트 프로젝트에서 `application.properties` 의 설정을 통해 데이터베이스와 연결

[BE] 데이터베이스 생성 및 스프링부트 연결하기

---

backend/build.gradle
backend/src/main/java/com/codesquad/todolist/TodolistApplication.java
backend/src/main/java/com/codesquad/todolist/config/SwaggerConfig.java

- `SwaggerConfig` 클래스 추가 및 `Docket` Bean 추가
- `Swagger` 내 API 정보를 보이기 위한 `ApiInfo` 인스턴스 생성

[BE] API 문서화를 위한 Swagger 설정 추가

---

backend/src/main/java/com/codesquad/todolist/card/Card.java
backend/src/main/java/com/codesquad/todolist/card/CardController.java
backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
backend/src/main/java/com/codesquad/todolist/card/CardService.java
backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
backend/src/test/java/com/codesquad/todolist/card/integration/CardServiceTest.java
backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java

칸반보드의 카드에 해당하는 도메인 객체인 `Card` 클래스 추가와,
관련된 레이어 클래스를 추가합니다.
- 도메인 클래스 `Card` 추가 및 `CardController`, `CardService`, `CardRepository` 추가
- `Card` 도메인과 관련된 단위/통합 테스트 클래스 추가 
resolve #23

[BE] 도메인 객체 추가 및 레이어 클래스 추가

---

backend/build.gradle
backend/src/main/java/com/codesquad/todolist/card/Card.java
backend/src/main/java/com/codesquad/todolist/card/CardController.java
backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
backend/src/main/java/com/codesquad/todolist/card/CardService.java
backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
backend/src/main/java/com/codesquad/todolist/exception/GlobalExceptionHandler.java
backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java

- CardCreateRequest의 getContent 수정 
- CardServiceTest, CardRepositoryTest 수정

[BE] 2차 PR 피드백 적용

---

backend/src/main/java/com/codesquad/todolist/card/CardController.java
backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
backend/src/main/java/com/codesquad/todolist/card/CardService.java
backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java

카드 삭제 기능을 구현하고, 단위&통합 테스트를 작성하였습니다.

[BE] 카드 삭제 기능 구현 및 테스트코드 작성

---

backend/src/main/java/com/codesquad/todolist/config/DateTimeConfig.java
backend/src/main/java/com/codesquad/todolist/config/SwaggerConfig.java
backend/src/main/java/com/codesquad/todolist/history/ModifiedFieldRepository.java
backend/src/main/java/com/codesquad/todolist/util/page/Slice.java
backend/src/main/resources/application.properties
backend/src/test/java/com/codesquad/todolist/history/unit/HistoryServiceTest.java

이전 PR 에서 fix 하지 못한  DateTimeFormat 수정과 History 페이징 시 Internal Server Error 발생을 수정합니다.
- Swagger Configuration 수정
- DateTime Configuration 추가
- History 페이징 시 Internal Server Error 발생 문제 수정
- `application.properties` 내 jackson, swagger 설정 추가

[BE] DateTime 포맷 및 History 페이징 수정 

---

backend/src/main/java/com/codesquad/todolist/card/Card.java
backend/src/main/java/com/codesquad/todolist/card/CardController.java
backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
backend/src/main/java/com/codesquad/todolist/card/CardService.java
backend/src/main/java/com/codesquad/todolist/card/dto/CardResponse.java
backend/src/main/java/com/codesquad/todolist/column/Column.java
backend/src/main/java/com/codesquad/todolist/column/ColumnController.java
backend/src/main/java/com/codesquad/todolist/column/ColumnRepository.java
backend/src/main/java/com/codesquad/todolist/column/ColumnService.java
backend/src/main/java/com/codesquad/todolist/column/dto/ColumnResponse.java
backend/src/main/java/com/codesquad/todolist/history/HistoryController.java
backend/src/main/java/com/codesquad/todolist/history/ModifiedFieldRepository.java
backend/src/main/java/com/codesquad/todolist/history/domain/ModifiedField.java
backend/src/main/java/com/codesquad/todolist/util/page/Criteria.java
backend/src/main/resources/data.sql
backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
backend/src/test/java/com/codesquad/todolist/column/unit/ColumnServiceTest.java

현재 PR 에서는 크게 아래의 2가지 기능을 구현했습니다.
- Column 별로 Card 출력 기능 추가
- Card CRUD 시 History 응답 기능 추가
세부 구현 사항으로는 아래와 같습니다.
- Column, Card 의 도메인 클래스 수정 및 DTO 추가
- Column, Card, ModifiedField 의 리포지토리 메서드 추가
- ColumnService 의 단위 테스트 추가
- `data.sql` 의 샘플 데이터 추가
Column 별로 Card 출력 응답
Card CRUD 시 History 응답

[BE] Column 별로 Card 출력 기능 추가 및 Card CRUD 시 History 응답 기능 추가

---

frontend/src/js/app.js
frontend/src/js/dragNdrop.js
frontend/src/scss/style.scss

구현이 덜 되어있는데 upstream 리뷰를 받기 위하여 머지받고자 PR올립니다!
머지후 개선하겠습니다.
https://user-images.githubusercontent.com/58525009/163114042-bf3db261-2364-4870-b80f-c5fe429fa83a.mp4

[FE] 드래그앤 드롭 기본 기능 구현(도착 잔상 및 맨끝에 추가 제외)

---

frontend/src/js/Controller/Controller.js
frontend/src/js/Todo/Card/Model.js
frontend/src/js/Todo/Card/View.js
frontend/src/js/Todo/Card/main.js
frontend/src/js/Todo/Column/Model.js
frontend/src/js/Todo/Column/View.js
frontend/src/js/Todo/Column/main.js
frontend/src/js/Todo/Model.js
frontend/src/js/Todo/View.js
frontend/src/js/Todo/main.js
frontend/src/js/Utils/template.js
frontend/src/js/app.js
frontend/src/scss/style.scss

카드추가 기능 구현 완료했습니다.
카드 컬럼에 추가 후 히스토리 내역에는 아직 추가 안했습니다..
https://user-images.githubusercontent.com/68211156/163015301-9a056b3e-b531-4298-bd3f-22f47a8a4ee0.mov

[FE] 카드 추가 기능 구현

---

backend/src/main/java/com/codesquad/todolist/card/CardController.java
backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
backend/src/main/java/com/codesquad/todolist/card/dto/CardMoveRequest.java
backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
backend/src/main/java/com/codesquad/todolist/column/ColumnController.java
backend/src/main/java/com/codesquad/todolist/history/HistoryController.java

Swagger 를 이용한 API 문서화를 위해,
`springfox-boot-starter` 라이브러리에서 제공하는 어노테이션 기반 API 세부 설명 작성을 완료했습니다.
- Controller 계층에서 API 설명 작성
- HTTP 요청을 body 로 받는 DTO 내에 스키마에 대한 설명 작성
- HTTP 요청을 parameter 로 받는 변수에 대한 설명 작성

[BE] API 문서화를 위한 Swagger 어노테이션 추가

---

backend/src/main/resources/application-local.properties
backend/src/main/resources/application-prod.properties
backend/src/main/resources/application.properties

제곧내 (application.properties 에서 DB 계정 정보를 local, prod 로 분리했다는 뜻)

[BE] application.properties 에서 DB 계정 정보를 local, prod 로 분리

---

backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
backend/src/main/java/com/codesquad/todolist/card/dto/CardMoveRequest.java
backend/src/main/resources/application-prod.properties

`application-prod.properties` 내 계정 정보를 변경하고,
swagger docs 에서 HTTP 요청 body 에 포함된 nextId 의 필수 조건을 제외했습니다.

[BE] application-prod.properties 내 계정 수정 및 swagger docs 수정

---

backend/src/main/java/com/codesquad/todolist/card/CardController.java
backend/src/main/java/com/codesquad/todolist/card/CardService.java
backend/src/main/java/com/codesquad/todolist/column/ColumnService.java
backend/src/main/java/com/codesquad/todolist/history/HistoryService.java

3차 PR 피드백 반영 시 사소한 수정 사항들을 묶어 프로젝트 내에 추가했습니다.
- CardController 에서 wildcard parameterized type 제거
- CardController 에서 카드 삭제 응답 시 HTTP 상태 204 가 아닌 200 응답으로 수정
- Service 계층의 메서드 내에 주석 추가

[BE] 3차 PR 피드백 적용

---

frontend/src/js/Controller/Controller.js
frontend/src/js/Todo/Card/View.js
frontend/src/js/Todo/View.js
frontend/src/scss/style.scss

카드 수정기능 완료
- 카드 write 모드일 때 스타일 적용 안했던 부분이 있어서 추가했습니다. (card border)
- 수정기능을 추가하면서 취소버튼 클릭 이벤트가 CardView에서 등록하고있었는데 버그를 발견했습니다..😭 
container 클릭이벤트에서 처리하도록 변경했습니다.
https://user-images.githubusercontent.com/68211156/163227604-3b769f86-35ee-46b6-8a4a-2699af0a3348.mov

[FE] 카드 수정기능 구현

---

backend/src/main/java/com/codesquad/todolist/config/WebMvcConfig.java

WebMvcConfigurer 구현체인 WebMvcConfig 에서 CORS Mapping 설정을 추가합니다.

feat: [#77] WebMvcConfig 내 addCorsMapping 추가

---

frontend/src/js/Controller/Controller.js
frontend/src/js/Utils/api.js

[FE] 카드 추가, 수정, 삭제 요청 구현

---

frontend/src/js/Controller/Controller.js
frontend/src/js/History/Model.js
frontend/src/js/History/View.js
frontend/src/js/History/main.js
frontend/src/js/Utils/template.js

[FE] 초기 히스토리 렌더

---

frontend/src/js/Controller/Controller.js
frontend/src/js/History/Model.js
frontend/src/js/History/View.js
frontend/src/js/Utils/api.js

[FE] 카드 추가, 수정, 삭제시 히스토리에 반영

---

frontend/src/js/Controller/Controller.js
frontend/src/js/History/Model.js
frontend/src/js/History/View.js
frontend/src/js/Todo/Model.js
frontend/src/js/Utils/api.js
frontend/src/scss/style.scss

[FE] 히스토리 렌더 완료
